export { default as cross } from './cross'
export { default as inverse } from './inverse'
export { default as matMult } from './matMult'
export { default as adjugate } from './adjugate'
export { default as determinant } from './determinant'
