export { default as cos } from './cos'
export { default as exp } from './exp'
export { default as max } from './max'
export { default as mean } from './mean'
export { default as norm } from './norm'
export { default as sin } from './sin'
export { default as sum } from './sum'
export { default as min } from './min'
