export { default as min } from './min'
export { default as sin } from './sin'
export { default as max } from './max'
export { default as sum } from './sum'
export { default as mean } from './mean'
export { default as norm } from './norm'
